apiVersion: apps/v1
kind: Deployment
metadata:
  name: minha-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minha-app
  template:
    metadata:
      labels:
        app: minha-app
  spec:
    containers:
    - name: minha-app
      image: minha-app:$(BUILD_ID}
      ports:
      - containerPort: 3000